In [1]:
import tinytensor as tt
import torch

In [2]:
x = tt.Tensor([1,2,3,4,5], dtype=tt.uint64, device="cuda")
y = tt.Tensor([2,3,4,5,6], dtype=tt.int8, device="cuda")
tx = torch.tensor([1,2,3,4,5])
ty = torch.tensor([2,3,4,5,6])

In [3]:
x.bitwise_and(y)

Tensor(shape=Shape(shape=(5,), ndim=1, size=5, stride=(1,)), dtype='unsigned long', device=Device(type=CUDA, index=0), requires_grad=False, const=False)

In [4]:
x.bitwise_and(y).data(), tx.bitwise_and(ty)

([0, 2, 0, 4, 4], tensor([0, 2, 0, 4, 4]))

In [5]:
x.bitwise_or(y).data(), tx.bitwise_or(ty)

([3, 3, 7, 5, 7], tensor([3, 3, 7, 5, 7]))

In [6]:
x.bitwise_xor(y).data(), tx.bitwise_xor(ty)

([3, 1, 7, 1, 3], tensor([3, 1, 7, 1, 3]))

In [7]:
x.bitwise_nand(y).data(), torch.bitwise_not(tx.bitwise_and(ty))

(['1.84e+19', '1.84e+19', '1.84e+19', '1.84e+19', '1.84e+19'],
 tensor([-1, -3, -1, -5, -5]))

In [8]:
x.bitwise_nor(y).data(), torch.bitwise_not(tx.bitwise_or(ty))

(['1.84e+19', '1.84e+19', '1.84e+19', '1.84e+19', '1.84e+19'],
 tensor([-4, -4, -8, -6, -8]))

In [9]:
x.bitwise_xnor(y).data(), torch.bitwise_not(tx.bitwise_xor(ty))

(['1.84e+19', '1.84e+19', '1.84e+19', '1.84e+19', '1.84e+19'],
 tensor([-4, -2, -8, -2, -4]))

In [10]:
x.bitwise_not().data(), tx.bitwise_not()

(['1.84e+19', '1.84e+19', '1.84e+19', '1.84e+19', '1.84e+19'],
 tensor([-2, -3, -4, -5, -6]))

In [11]:
y.bitwise_not().data(), ty.bitwise_not()

([-3, -4, -5, -6, -7], tensor([-3, -4, -5, -6, -7]))

In [12]:
x.logical_and(y).data(), tx.logical_and(ty)

([True, True, True, True, True], tensor([True, True, True, True, True]))

In [13]:
x.logical_and(y).data(), tx.logical_and(ty)

([True, True, True, True, True], tensor([True, True, True, True, True]))