In [1]:
import tinytensor as tt
import torch

In [2]:
tt.__version__

'0.3.0+cu131'

In [3]:
torch.__version__

'2.10.0+cu128'

In [4]:
x = tt.Tensor([1+3j, -3+7j], device="cuda")
y = tt.Tensor([0.5-.1j, 0.23+1j], device="cuda")
a = torch.tensor([1+3j, -3+7j])
b = torch.tensor([0.5-.1j, 0.23+1j])

In [5]:
x.sin().data(), a.sin()

(['8.4716+5.4127j', '-77.3785-542.8289j'],
 tensor([  8.4716+5.4127j, -77.3785-542.8289j]))

In [6]:
x.cos().data(), a.cos()

(['5.4396-8.4298j', '-542.8297+77.3784j'],
 tensor([   5.4396-8.4298j, -542.8297+77.3784j]))

In [7]:
x.tan().data(), a.tan()

(['-0.0021-1.0021j', '2e-06-1.0j'],
 tensor([4.5171e-03+1.0021j, 4.6468e-07+1.0000j]))

In [8]:
y.asin().data(), b.asin()

(['0.5198-0.115j', '0.1623+0.8908j'], tensor([0.5198-0.1150j, 0.1623+0.8908j]))

In [9]:
y.acos().data(), b.acos()

(['1.0510+0.115j', '1.4085-0.8908j'], tensor([1.0510+0.1150j, 1.4085-0.8908j]))

In [10]:
y.atan().data(), b.atan()

(['1.0510+0.115j', '1.4085-0.8908j'], tensor([0.4669-0.0800j, 0.8426+1.0847j]))

In [11]:
x.sinh().data(), a.sinh()

(['-1.1634+0.2178j', '-7.5525+6.6143j'],
 tensor([-1.1634+0.2178j, -7.5525+6.6143j]))

In [12]:
x.cosh().data(), a.cosh()

(['-1.5276+0.1658j', '7.5900-6.5816j'],
 tensor([-1.5276+0.1658j,  7.5900-6.5816j]))

In [13]:
x.tanh().data(), a.tanh()

(['0.7680-0.0592j', '-0.9993+0.0049j'],
 tensor([ 0.7680-0.0592j, -0.9993+0.0049j]))

In [14]:
y.asinh().data(), b.asinh()

(['0.4830-0.0895j', '0.4883+1.1008j'],
 tensor([0.4830-0.0895j, 0.4883+1.1008j]))

In [15]:
x.acosh().data(), a.acosh()

(['1.8642+1.2632j', '2.7263+1.9726j'],
 tensor([1.8642+1.2632j, 2.7263+1.9726j]))

In [16]:
x.atanh().data(), a.atanh()

(['0.0919+1.2768j', '-0.0510+1.4504j'],
 tensor([ 0.0919+1.2768j, -0.0510+1.4504j]))